---
name: Solid Test Suites

on:
  push:
    branches:
      - main
      - cleanup/ci # @TODO: Remove this before merging to main
  pull_request:
    branches: [ main ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # @TODO: Instead of building the docker image here, take a pre-build image and mount the code (only build when the Dockerfile changes)
  build-docker-nextcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Solid-Nextcloud Docker image
        run: |
          docker build -t "ghcr.io/pdsinterop/solid-nextcloud:${{ github.sha }}" .
          docker push "ghcr.io/pdsinterop/solid-nextcloud:${{ github.sha }}"

  solid-testsuite:
    strategy:
      fail-fast: false
      matrix:
        test:
          - 'solidtestsuite/solid-crud-tests:v7.0.5'
          - 'solidtestsuite/web-access-control-tests:v7.1.0'
          - 'solidtestsuite/webid-provider-tests:v2.1.0'

    needs:
      - build-docker-nextcloud

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker Images
        run: |
          docker pull michielbdejong/nextcloud-cookie
          docker pull ${{ matrix.test }}
          docker pull ghcr.io/pdsinterop/solid-nextcloud:${{ github.sha }}
          docker pull ghcr.io/pdsinterop/php-solid-pubsub-server:latest

      - name: Start Docker Containers
        run: |
          docker network create testnet
          docker run -i --network=testnet -d --name 'pubsub' "ghcr.io/pdsinterop/php-solid-pubsub-server:latest"

          source ./run-solid-test-suite.sh
          startSolidNextcloud 'server' "ghcr.io/pdsinterop/solid-nextcloud:${{ github.sha }}" ${{ matrix.test }}
          startSolidNextcloud 'thirdparty' "ghcr.io/pdsinterop/solid-nextcloud:${{ github.sha }}" ${{ matrix.test }}

          echo "COOKIE_server=${COOKIE_server}" >> "${GITHUB_ENV}"
          echo "COOKIE_thirdparty=${COOKIE_thirdparty}" >> "${GITHUB_ENV}"

      - name: Run tests - ${{ matrix.test }}
        run: |
          export COOKIE_server="${{ env.COOKIE_server }}"
          export COOKIE_thirdparty="${{ env.COOKIE_thirdparty }}"

          docker run -i --rm --network=testnet \
            --name tester \
            --env COOKIE="$COOKIE_server" \
            --env COOKIE_ALICE="$COOKIE_server" \
            --env COOKIE_BOB="$COOKIE_thirdparty" \
            --env-file ./env-vars-testers.list \
            ${{ matrix.test }}
