# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
    - main
    - cleanup/ci
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Solid test suite
        shell: 'script -q -e -c "bash {0}"'
        run: >-
          source ./run-solid-test-suite.sh
          && setup
          && startPubSub
          && startSolidNextcloud server
          && startSolidNextcloud thirdparty

      - name: Run the Solid test suite
        shell: 'script -q -e -c "bash {0}"'
        run: >-
          source ./run-solid-test-suite.sh
          && runTests webid-provider
          && runTests solid-crud
          && runTests web-access-control
