---
name: Linting jobs

on:
  - push
  - pull_request

jobs:
  lint-json:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: "docker://pipelinecomponents/jsonlint:latest"
        with:
          args: "find . -not -path './.git/*' -name '*.json' -type f"

  lint-php:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pipeline-components/php-linter@master

  lint-yaml:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint --config-file=build/.yamllint .
