---
name: Quality Assurance jobs

on:
  - push
  - pull_request

jobs:
  composer-validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: "docker://composer"
        with:
          args: composer validate --strict --working-dir=solid/
